# Generated by Django 4.2.7 on 2023-12-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=255)),
                ('work_order_number', models.CharField(max_length=50)),
                ('surface_plate_id', models.CharField(max_length=50)),
                ('surface_plate_type', models.CharField(max_length=50)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.CharField(max_length=50)),
                ('along_rows', models.JSONField()),
                ('across_rows', models.JSONField()),
            ],
        ),
    ]
