# Generated by Django 4.2.7 on 2023-12-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csurflat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='bridge_length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='end_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='num_cols',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='num_rows',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='ref',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='start_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='across_rows',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='along_rows',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='grade',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='surface_plate_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='surface_plate_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
