# Generated by Django 4.2.7 on 2023-12-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csurflat', '0002_workorder_bridge_length_workorder_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='across_rows',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='along_rows',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='bridge_length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='description',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='end_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='grade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='num_cols',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='num_rows',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='start_temp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='surface_plate_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='surface_plate_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
