# Generated by Django 4.2.7 on 2023-12-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csurflat', '0003_alter_workorder_across_rows_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='across_rows',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='along_rows',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
