# Generated by Django 4.2.7 on 2023-12-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csurflat', '0004_alter_workorder_across_rows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='flatness',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
